[features]
seeds = false
skip-lint = false
[programs.localnet]
backend = "13YVuPAdZDTe1xssYDwTg6ndGFhhSMv3tZxh8s2wyZMA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cristobal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
