[features]
seeds = true
skip-lint = false
[programs.localnet]
backend = "8ptgSjCeuciKorgFjNhE1kpFrSnG2s5A1gEBBcczgVGH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
